Fix Jitpack not compiling
korlibs/korge-luak pull request #14
Opened 2023-12-23 00:06 UTC by DersWasTaken

Mentioned [here](https://github.com/korlibs/korge-luak/issues/13) 

Finally had some time to sit down and figure out how jitpack works, not sure if all my changes are required, but I need to go to bed, ill experiment with it tomorrows. 

I couldn't get it to compile with targetAndroid, though it may be different for you.

Hope this helps! Let me know if any changes are needed, I can try and see if I can get it to work with targetAndroid.

2023-12-23 08:11 UTC, soywiz commented on build.gradle.kts
> -    targetAndroidDirect()
https://docs.jitpack.io/building/#:~:text=these%20environment%20variables%3A-,JITPACK%3Dtrue,-JAVA_HOME%3D%3Cdetected%20java

```kotlin
if (System.getenv("JITPACK") != "true") {
  targetAndroidDirect()
}
```

2023-12-23 18:02 UTC, DersWasTaken commented on build.gradle.kts
> -    targetAndroidDirect()
![image](https://github.com/korlibs/korge-luak/assets/85004622/a5b179d2-8f33-4248-9bb5-efad29380f7c)
Failed on my end at 95%, probably a issue with my machine.

It builds just fine on jitpack though, so who knows.

2023-12-23 18:03 UTC, DersWasTaken commented on build.gradle.kts
> -    targetAndroidDirect()
https://jitpack.io/#DersWasTaken/korge-luak/dc152b5fdf

2023-12-23 20:55 UTC, DersWasTaken commented on build.gradle.kts
> -    targetAndroidDirect()
Figured out that I should use my eyes, changed != to ==.
builds fine for me now and still works on jitpack.

2023-12-24 08:07 UTC, soywiz commented on build.gradle.kts
> -    targetAndroidDirect()
The idea is that the android target is available when jitpack is not there. If it is failing on your machine with that line, that's a separate issue. Can you run gradlew with --stacktrace and --info? Like: `./gradlew --stacktrace --info ` + the task. And provide the stacktrace so we can try to figure out why?

2023-12-24 16:44 UTC, DersWasTaken commented on build.gradle.kts
> -    targetAndroidDirect()
https://scans.gradle.com/s/5ftnybietxtzc

2023-12-24 18:58 UTC, DersWasTaken commented on build.gradle.kts
> -    targetAndroidDirect()
Adding 
```kts
afterEvaluate {
    tasks.getByName<AndroidLintAnalysisTask>("lintVitalAnalyzeRelease") {
        dependsOn(tasks.getByName("jvmProcessResources"))
    }
}
```

Seems to work. Not sure if this causes any conflicts though.

2023-12-26 19:16 UTC, soywiz requested changes
Please, remove the gradle wrapper, gradlew and gradlew.bat changes as they cannot be accepted in this PR

2023-12-26 19:16 UTC, soywiz commented on gradle/wrapper/gradle-wrapper.jar
Cannot accept this kind of binary files here.

2023-12-26 19:44 UTC, DersWasTaken commented on gradle/wrapper/gradle-wrapper.jar
To confirm you want the gradle wrapper, gradlew, and gradlew.bat changes reverted? 

I dont even remember changing them so I can do that. Is there anything else?

2023-12-26 20:03 UTC, DersWasTaken commented on gradle/wrapper/gradle-wrapper.jar
Should be fixed in newest commit unless I missed something and or you wanted gradle.properties  returned

2023-12-26 20:04 UTC, DersWasTaken commented on gradle/wrapper/gradle-wrapper.jar
Im apparently terrible at git commands, as you can see by my three commits it took to rollback changes

2023-12-29 08:13 UTC, soywiz requested changes
Sorry for the delay. Just triggered the CI build and it is not passing because the `gradlew` file was removed as executable. Please revert the `gradlew` change or add the executable flag again as suggested in the comment of the file.

2023-12-29 08:13 UTC, soywiz commented on gradlew
CI is broken because here the executable flag was removed: https://github.com/korlibs/korge-luak/actions/runs/7332265523/job/20022856685#step:4:25

If you ware using windows, please execute this command (or revert this file):
```
git update-index --chmod=+x gradlew
```

2023-12-30 16:27 UTC, DersWasTaken commented on gradlew
Done!

2023-12-30 18:13 UTC, soywiz approved these changes

2023-12-30 18:13 UTC, merged

2023-12-30 18:13 UTC, soywiz commented
Thanks!